Add alloca.h include for Linux ALSA support
Fixes linker error on ARM64 Linux:
  undefined reference to 'alloca'

The snd_mixer_selem_id_alloca() macro requires alloca.h on Linux.